# Generated by Django 5.2 on 2025-04-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
